### ISSUE TITLE
Revise keys in number-compare-strings_en.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/number-compare#14]
From the CRC:
>  Make sure the string keys are all perfect, because they are difficult to change after 1.0.0 is published. Guidelines for string keys are:
> 
> (1) Strings keys should generally match their values. E.g.:
> 
> ```
> "helloWorld": {
>   value: "Hello World!"
> },
> "quadraticTerms": {
>   value: "Quadratic Terms"
> }
> ```

Inspecting number-compare-strings_en.json, these 2 strings keys should be changed to match their values. The keys should be "isGreaterThan" and "hearNumberSentence" respectively.  @chrisklus do you agree? 

```
  "isMoreThan": {
    "value": "{{greaterNumber}} is greater than {{smallerNumber}}"
  },

 "readAloud": {
    "value": "Hear Number Sentence"
  }
```

**Comment by pixelzoom** [comment]
I took care of this in the above commit. @chrisklus please review. Close if OK.

**Comment by chrisklus** [comment]
Thanks @pixelzoom, commits look great. `"isMoreThan"` also needed to be renamed in babel since that string was already published. But I double checked the commit history (in number-play-strings_en.json since it was originally published as part of Number Play), and the string value was changed to `"{{greaterNumber}} is greater than {{smallerNumber}}"` before publication, so the translated values are correct, just the keys needed to be updated.

I think we are all set to close here.
