### ISSUE TITLE
What should happen to the objects located in the Paper Ones Toolbox area when "Show Ones" is switched back? on?

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/number-compare#33]
**Test device**
MacBook Air (m1 chip)

**Operating System**
13.2.1

**Browser**
Chrome 

**Problem description**
For https://github.com/phetsims/qa/issues/917, when "Show Ones" is off, I am able to  place objects to the right of the Balls Toolbox (except for the 10 frame). Turning "Show Ones" back on, results in those objects being in front of the Paper Ones Toolbox. 

**Steps to reproduce**
1. Turn off "Show Ones" in the Simulation tab
2. On the lab screen, add objects to the right of the Balls Toolbox. 
3. Turn on "Show Ones"

**Visuals**
<img width="506" alt="Screenshot 2023-03-19 at 2 08 19 PM" src="https://user-images.githubusercontent.com/87318828/226197953-8dd3157f-55ca-43e9-bd07-a30a57a2294e.png">

<img width="506" alt="Screenshot 2023-03-19 at 2 08 39 PM" src="https://user-images.githubusercontent.com/87318828/226197966-e0375c55-8df8-4ddd-80e1-5bf87d84402b.png">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Number Compare‬
URL: https://phet-dev.colorado.edu/html/number-compare/1.0.0-dev.6/phet/number-compare_all_phet.html
Version: 1.0.0-dev.6 2023-03-15 01:30:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
Language: en-US
Window: 1512x773
Pixel Ratio: 1.7999999523162842/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by amanda-phet** [comment]
Discussed with @chrisklus and @marlitas and see three potential directions: 
(1) Leave this as-is, and the user can move them out of the way or tap them to return them home. This is the easiest and least expensive option. 
(2) Return the objects to their creator node. This feels rude, and a user might not even see their objects fly home because it would happen while preferences is open. 
(3) Push the objects out of the way. This could be the best UX, but seems like it opens us up to lots of complications. 

Decision: (1) Leave this as it is.
